FROM java:8
VOLUME /tmp
ADD whayaAPIAuth-0.0.1-SNAPSHOT.jar whayaAPIAuth-0.0.1-SNAPSHOT.jar
RUN bash -c 'touch /whayaAPIAuth-0.0.1-SNAPSHOT.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/whayaAPIAuth-0.0.1-SNAPSHOT.jar"]