FROM java:8
VOLUME /tmp
ADD Zuul-0.0.1-SNAPSHOT.jar Zuul-0.0.1-SNAPSHOT.jar
RUN bash -c 'touch /Zuul-0.0.1-SNAPSHOT.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/Zuul-0.0.1-SNAPSHOT.jar"]