FROM neo4j:3.1.4
MAINTAINER Manel Mena Vicente manel.mena@ual.es

ENV APOC_RELEASE 3.1.3.7
ENV APOC_RELEASES_URL https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download
ENV APOC_PLUGIN_JAR apoc-${APOC_RELEASE}-all.jar
ENV APOC_PLUGIN_URL ${APOC_RELEASES_URL}/${APOC_RELEASE}/${APOC_PLUGIN_JAR}

RUN apk update \
    && apk add ca-certificates wget \
    && update-ca-certificates \
    && apk add openssl curl

RUN apk add --update zip unzip && rm -rf /var/cache/apk/*

RUN curl -s -L -o /var/lib/neo4j/plugins/neo4j-spatial-server-plugin.jar https://github.com/neo4j-contrib/spatial/files/1227950/neo4j-spatial-0.24-neo4j-3.1.4-server-plugin.zip

RUN curl --output /var/lib/neo4j/plugins/${APOC_PLUGIN_JAR} --location "${APOC_PLUGIN_URL}?raw=true"


#RUN sed -i "s|dbms.memory.heap.max_size=512M|dbms.memory.heap.max_size=4096M|g" /var/lib/neo4j/conf/neo4j.conf
#RUN wget http://apache.rediris.es/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
#RUN tar xzvf apache-maven-3.5.0-bin.tar.gz
#RUN cp -r ./apache-maven-3.5.0 /usr/lib/
#ENV PATH="/usr/lib/apache-maven-3.5.0/bin:${PATH}"


