FROM java:8
VOLUME /tmp
ADD whayaAPIMongo-0.0.1.jar whayaAPIMongo-0.0.1.jar
RUN bash -c 'touch /whayaAPIMongo-0.0.1.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/whayaAPIMongo-0.0.1.jar"]