FROM java:8
VOLUME /tmp
ADD Eureka-0.0.1-SNAPSHOT.jar Eureka-0.0.1-SNAPSHOT.jar
RUN bash -c 'touch /Eureka-0.0.1-SNAPSHOT.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/Eureka-0.0.1-SNAPSHOT.jar"]