FROM java:8
VOLUME /tmp
ADD Hystrix-0.0.1-SNAPSHOT.jar Hystrix-0.0.1-SNAPSHOT.jar
RUN bash -c 'touch /Hystrix-0.0.1-SNAPSHOT.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/Hystrix-0.0.1-SNAPSHOT.jar"]